name: 'Plagiarism checker'
description: 'Detect plagiarism among pull requests solutions'
inputs:
  github-access-token:
    description: 'GitHub access token'
    required: true
  repository-name:
    description: 'Name of repository'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-access-token }}
    - ${{ inputs.repository-name }}